ServoCamera:
  pub_topic_scam:
    pub_servo_angle : '/servo_angle' 


  sub_topic_scam:
    sub_control : '/servo_control' # 2 bit, 1.rotate 2.seeing artag


  Baudrate:
    baudrate: '9600'


  ports:
    servoport : '/dev/ttyUSB0'


